#!/bin/bash
git clone  --no-checkout -o origin  https://github.com/yade/trunk
cd trunk
version=$(git describe --tags|cut -c -12)$(git rev-parse HEAD|cut -c -7)~$1
date=$(date +"%a, %d %b %Y %X %z")
echo $date
git clone https://github.com/remche/yadedaily.git debian
git -C debian checkout remotes/origin/$1

sed -i.bak -e s/VERSION/$version/ -e s/DISTRIBUTION/$1/ -e s/DATE/"$date"/ debian/changelog
sed -i.bak -e s/VERSIONYADEREPLACE/$version/ debian/rules

git checkout -b debian/$1 origin/master 
gbp buildpackage --git-ignore-new  --git-no-pristine-tar --git-debian-branch=debian/jessie --git-upstream-tag='master'
