# Dockerfile
FROM ubuntu:16.04


RUN apt-get clean && apt-get update && apt-get install -y \ 
    gnupg \
    wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "deb http://www.yade-dem.org/packages/ xenial/" >> /etc/apt/sources.list

RUN wget -O - http://www.yade-dem.org/packages/yadedev_pub.gpg |apt-key add -
