# docker-compose.yml
version: '2'
services:
    yade: 
      build:
        context: .
        dockerfile: Dockerfile-${DISTR}
      image: yade-${DISTR}
      command: ./test.sh ${DISTR}
      volumes: 
          - ./pkg-${DISTR}:/data 
      working_dir: /data
      command: build-yade-package ${DISTR}
