# Dockerfile
FROM debian:unstable

RUN sed -i "s/httpredir/ftp.fr/" /etc/apt/sources.list

RUN apt-get clean && apt-get update && apt-get install -y \ 
    gnupg \
    wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "deb http://www.yade-dem.org/packages/ unstable/" >> /etc/apt/sources.list

RUN wget -O - http://www.yade-dem.org/packages/yadedev_pub.gpg | apt-key add -
