# docker-compose.yml
version: '2'
services:
    yade: 
      build:
        context: .
        dockerfile: Dockerfile-${DISTR}
      image: yade-${DISTR}
      container_name: yade-${DISTR}
      volumes: 
          - /tmp/pkg-${DISTR}:/data 
          - ${HOME}/.gnupg:/root/.gnupg
      working_dir: /data
      command: build-yade-package ${DISTR}
